components:
  parameters:
    Id:
      name: id
      in: path
      required: true
      description: Id of a resource
      schema:
        type: string
        example: 64a41dab-0c61-478d-88c7-e74c7e1751f9
